name: CICD
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build .

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with docker compose
        run: docker compose build
      - name: Run tests
        run: docker compose run --rm api pnpm test
      - name: Cleanup
        run: docker compose down

  # TODO
  # deploy:
  #   needs: [test]
  #   runs-on: ubuntu-latest
